### ISSUE TITLE
Crowd Import error

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#135]
Trying to import crowd data but getting error.

https://github.com/clinwiki-org/clinwiki/blob/master/imports/Musella%20Import%2020180628.csv

Sample Row:

NCT00001595 | GBM Prior Therapy Gliadel | Unknown | Add

Error:
{:nct_id=>"NCT00001595", :error=>#<RuntimeError: Type GBM Prior Therapy Gliadel unsupported>}

**Comment by relwell** [comment]
So per the README:

> We support `Tags` as a type, with `Add` or `Remove` as an action.
> For crowd values, we only presently support native fields that are
> crowd overwriteable.

So this means that what you're trying to do isn't presently supported in the CSV import.

I'm going to try to add in functionality to support crowd data. I think there was a reason we only supported crowd data that corresponded to fields in AACT, but I'll dig in and try to validate.

**Comment by relwell** [comment]
I pushed an update to the import logic, and also ran the import locally and validated that it worked correctly. I'm going to import on prod now.

**Comment by relwell** [comment]
Okay, the import succeeded with the following output:
{code}
[{:nct_id=>"NCT02430727", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02439268", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02644512", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02899715", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01226940", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT00452959", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT00831324", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01386450", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01586078", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01226940", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01586078", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02644512", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT00452959", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT00831324", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01386450", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01586078", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02439268", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02644512", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02899715", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT00452959", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01586078", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02430727", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02439268", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02644512", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02899715", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT00831324", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01226940", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01386450", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01226940", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02430727", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02430727", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT00452959", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT00831324", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01226940", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01386450", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT01586078", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02430727", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02439268", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02644512", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}, {:nct_id=>"NCT02899715", :error=>#<NoMethodError: undefined method `wiki_page' for nil:NilClass>}]
{code}

In this case, these are acceptable errors because they indicate that we don't actually have an entry in AACT for those NCT IDs, and so we can't create a wiki page for them. The rest should be successfully saved and reindexing as we speak.

**Comment by relwell** [comment]
Just to confirm:

```
irb(main):002:0> Study.find_by(nct_id: 'NCT02439268')
  Study Load (7.9ms)  SELECT  "studies".* FROM "studies" WHERE "studies"."nct_id" = $1 LIMIT 1  [["nct_id", "NCT02439268"]]
=> nil
irb(main):003:0> Study.find_by(nct_id: 'NCT002439268')
  Study Load (9.5ms)  SELECT  "studies".* FROM "studies" WHERE "studies"."nct_id" = $1 LIMIT 1  [["nct_id", "NCT002439268"]]
=> nil
irb(main):004:0> Study.find_by(nct_id: 'NCT02644512')
  Study Load (8.8ms)  SELECT  "studies".* FROM "studies" WHERE "studies"."nct_id" = $1 LIMIT 1  [["nct_id", "NCT02644512"]]
=> nil
irb(main):005:0> Study.find_by(nct_id: 'NCT02899715')
  Study Load (7.8ms)  SELECT  "studies".* FROM "studies" WHERE "studies"."nct_id" = $1 LIMIT 1  [["nct_id", "NCT02899715"]]
=> nil
```

**Comment by williamhoos** [comment]
I think this is closed
