### ISSUE TITLE
Fix date display

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#184]
Start and completion date are not displaying correctly on search results page and study page, see below. Change format to just display date and not include time.

![Screen Shot 2019-10-29 at 12 16 45 PM](https://user-images.githubusercontent.com/43178464/67787067-4e4f8600-fa46-11e9-9c9d-7485d9a5e9b2.png)
![Screen Shot 2019-10-29 at 12 18 04 PM](https://user-images.githubusercontent.com/43178464/67787075-53143a00-fa46-11e9-94f0-b036104e70de.png)

**Comment by williamhoos** [comment]
Since we want this propagate everywhere in the site, let's confirm right place to fix it. @ericharding mentioned that it might be a field formatting at the rails or graphql level. Since we want date based facet on search page, having the date formatted and displayed right seems important.

**Comment by ericharding** [comment]
Right now the server sends down this info for a study:  There's an ISO format date time which is precise and a more human friendly monthYear.  As an API for other sites to consume it makes sense to send down the ISO time because that's easy for the client to parse and display how it wants to.  Right now we're just displaying it raw which doesn't look good.  

If we want to have a single canonical way to format the time we could format it on the server and send that down.  If, instead, we want to choose how we format the date everywhere that we display it it would make more sense for the client do to that.

{
  "data": {
    "study": {
      "completionDate": "2003-05-31T00:00:00Z",
      "completionDateType": "Actual",
      "completionMonthYear": "May 2003"
    }
  }
}

**Comment by williamhoos** [comment]
I want this to eventually be configurable via the subsites so we can have
multiple date formats. Not sure this would be done at server or client so
if we could do something to format all date values as mm/dd/yyyy at the web
display level for now that would be great

**Comment by CKH4** [comment]
Partially resolved by #199, but there is probably a better solution more related to the serialization of data sent over graphql
