### ISSUE TITLE
Redundant interventions listed in Interventions table

### ISSUE THREAD

**Issue by awestermann** [clinwiki-org/clinwiki#333]
interventions are repeated so many times in the Interventions table: https://musella.clinwiki.org/search/bI1k9l_D/study/NCT04049669/ https://musella.clinwiki.org/search/qsj_T.YN/study/NCT00075387 https://musella.clinwiki.org/search/qsj_T.YN/study/NCT00659126/

https://als.clinwiki.org/search/tUCvyf_v/study/NCT00912041 vs https://clinicaltrials.gov/ct2/show/NCT00912041

**Comment by williamhoos** [comment]
This is due to the query defining the intervention table on the study page. That query is in the study.rb page. https://github.com/clinwiki-org/clinwiki/commits/c3466b0c18f3b0bb2b1d03f80f5d10493abc52d4/app/models/study.rb

Cause of duplicate rows is because 
A) there are drugs used in multiple arms (design_groups) but the arm info is not displayed
B) "other names" causes duplication as well.

Need to identify a better way to display/manage the 1 to many data. 

This study is best example of the most complex study display and I think covers most of the issues.
Other issues include that sometimes arms and intreventions aren't listed correctly - it is a circular set of relational values with some values missing in some studies.

https://clinicaltrials.gov/ct2/show/NCT00075387

The heirarchy is (mostly):
design_groups
design_group_interventions
interventions
interventions_other_names

We start and left join on the interventions table to account for the studies that have no design groups. There are also studies with design_groups and no interventions that are not displaying correctly.

Example of missing design groups but intervention table values (not displayed in clinwiki currently because the dg.nct_id is the where clause for selecting rows to display):
NCT04221841
--modifying where clause to "dg.nct_id IN ('NCT04227080') or i.nct_id IN ('NCT04227080')" would return rows for this study. May not be right solution.

Example of missing intervention with design group values (not shown because join starts with intervention (not sure best way to resolve) - CTG appears to have different display method for studies without interventions
NCT04316949

current query:
 SELECT 
        --dg.group_type,
        --dg.title,
        --dg.description,
        --ion.name as other_name,
          i.id,
          i.name,
          i.intervention_type,
          i.description,
          i.nct_id
        FROM interventions i
        left outer join intervention_other_names ion
          on i.id = ion.intervention_id
        left outer join design_group_interventions dgi
          on i.id = dgi.intervention_id
        left outer join design_groups dg
        on dgi.design_group_id = dg.id
        where dg.nct_id IN ('NCT00912041')
        order by dg.group_type


groups only:
![image](https://user-images.githubusercontent.com/19411659/77231527-ebd06100-6b71-11ea-8c2d-d536b77ae4eb.png)


intervention only:
![image](https://user-images.githubusercontent.com/19411659/77231541-01de2180-6b72-11ea-86b6-08b131bbd1d8.png)


groups and interventions with other names:
![image](https://user-images.githubusercontent.com/19411659/77231559-1e7a5980-6b72-11ea-8870-8202858bc351.png)

**Comment by williamhoos** [comment]
Change Query to this in app/models/study.rb:
SELECT
i.id,
i.nct_id,
dg.group_type as "Group Type",
dg.title as "Arm Title",
i.intervention_type as "Intervention Type",
i.name as "Intervention Name"
FROM interventions i
left outer join design_group_interventions dgi
on i.id = dgi.intervention_id
left outer join design_groups dg
on dgi.design_group_id = dg.id
where 
dg.nct_id IN (#{ids_sql})
--dg.nct_id IN ('NCT00075387')
order by 
dg.group_type,
dg.title,
i.intervention_type,
i.name 

Change Intervention table to the columns in the query above:
In 
front/app/containers/InterventionsPage/InterventionsPage.tsx and front/app/containers/InterventionsPage/InterventionItem.tsx

From Name|Kind|Description 
to 
"Group Type"|"Arm Title"|"Intervention Type"|"Intervention Name"

Still want to onclick link to the Intervention page keyed of Intervention Name

**Comment by williamhoos** [comment]
As discussed ,hopefully fix is just inserting the tables that have the related content. The names of those colums are in sql above but here is visual from AACT schema.

the 4 tables to start:
interventions
design_group_interventions
design_groups
designs

(we may need to add intervention_other_names but hold for now)

Note the tables have a key relationship with the studies table and also with each other. Not sure how this is represented in graphql, so please confirm how/if those relationships get represented.

![image](https://user-images.githubusercontent.com/19411659/88336010-41747000-cd02-11ea-8c9e-8ce9fd8a8f51.png)

**Comment by williamhoos** [comment]
Depending how this gets implemented and how mailmerge ingests, we may have to modify the structure

**Comment by Tonyynot14** [comment]
@williamhoos In graphql currently study_type has a field for interventions, and a separate field called design on the same type but is just a string with "TBD" in it. I am looking into the best way to connect things back. Going to try some things out, but one types for each table are defiantly necessary so might start with the make basic way and iterate on changing it.

**Comment by Tonyynot14** [comment]
`study{
  designs{
    allocation
    interventionModel
    primaryPurpose
  }
  intervention{
    interventionType
    name
    description
    designGroupInterventions{
      designGroup{
        groupType
        title
        description
      }
    }
  }
}`
This would be my guess of how to but it up because the design is only connected to study, but the rest follow I kind of chain down from intervention to design group interventions(literally just a join table for design_group and intervention) and to design group.

**Comment by williamhoos** [comment]
Notes on hasura config:
setting up two directions:
studies-->interventions 
studies-->design_groups

notes:
for interventions, relationship circular so ensure doesn't break hasura or introspection. to handle missing, not sure what necessary, test studies include:  - note, when flowing through interventions, the design groups are grouped by intervention, not how we usually want to show it - to properly display, need "if...then" logic to show via design_groups and if missing, show just interventions
NCT04221841 - only has interventions - doesn't return any interventions when flowing through design groups but does through interventions
NCT04227080 - same as above
