### ISSUE TITLE
Implement Nesting  Index and Graphql

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#364]
First step of the history is getting the back end of wiki edits indexed with nesting functionality

**Comment by williamhoos** [comment]
@Tonyynot14 can you describe the approach to the nesting and custom elastic in this issue.

**Comment by williamhoos** [comment]
maybe post the sample graphiql query that can return the list of user emails and aggs, filtered for other agg values, that will be used to populate facets.

**Comment by Tonyynot14** [comment]
First, you have to make a custom mapping for the nested field so it can be indexed correctly. Then you have to append 
"aggs": {
    "wiki_page_edits": {
      "nested": {
        "path": "wiki_page_edits"
      },
 around the aggregation part of the query, that searchkick creates so that it searches correctly.  This is the elastic search query that would be called. 
curl http://localhost:9200/studies_development/_search?pretty -H 'Content-Type: application/json' -d '{
  "aggs": {
    "wiki_page_edits": {
      "nested": {
        "path": "wiki_page_edits"
      },
      "aggs": {
        "wiki_page_edits.email": {
          "filter": {
            "bool": {
              "must": [
                {
                  "bool": {
                    "must": []
                  }
                }
              ]
            }
          },
          "aggs": {
            "wiki_page_edits.email": {
              "terms": {
                "field": "wiki_page_edits.email",
                "size": 1000000
              }
            }
          }
        }
      }
    }
  },
  "query": {
    "bool": {
      "must": {
        "query_string": {
          "query": "*"
        }
      },
      "filter": [
        {
          "bool": {
            "must": []
          }
        }
      ]
    }
  },
  "sort": [
    {
      "nct_id": "asc"
    }
  ],
  "timeout": "11s",
  "size": 0,
  "from": 0
}'
