### ISSUE TITLE
password reset broken

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#398]
error on attempt to reset password for non-oauth loging

**Comment by Tonyynot14** [comment]
@ericharding @williamhoos Do we have logging on production that we can read the logs for 500 errors? Would help in finding the issue with password reset giving a 500 on production

**Comment by Tonyynot14** [comment]
If it does not find the user it works as expected so it seems to be a break at user.send_reset_password_instructions in the reset_password.rb mutation

**Comment by hifilorau** [comment]
1. Add new route for update password.
2. Create react view inside of LoginPage folder with mutation for updating pw. 
       - password confirmation. 
       - prep for getting token from url. 
       -(needs to be 8 characters long) (minor error validation can copy from user creation)
3.. Reroute email to new react view.
4.. Send token and new password to new rails endpoint.

**Comment by williamhoos** [comment]
to confirm, this will be the relatively "standard" - enter your email, get an email with a one time unique link, click on the link and enter the reset password in duplicate, save to profile and redirect to the previous page location, logged in?

Isn't there an "off the shelf" react/rails login management tool that we just wire into the application?

**Comment by hifilorau** [comment]
@williamhoos the flow you said is correct. I guess two minor caveats -
   1. Since you are coming from your email client and not just being rerouted to a signup page it's usually a whole new browser tab/window so there is no page to return to (plus they'd be returning to a sign up page in this case where the forgot password link lives). Most apps when you reset your password force you to immediately re-login with your new password so the plan was to just redirect to login. We could autolog people in from submission there pretty easily though also if that's the behavior we want. 
   2. The back end uses rails standard devise to handle some of the auth and to hook up to talk to your email sending client (in this case mailgun) All of that is pretty much standard.
   3. There isn't really an off the shelf react package to handle it on the react side. But it's not much different than any other form work. We rip the token from the URL and send that data along via a gql mutation and the new password. There are probably react packages that handle the validation of the two passwords matching but they aren't being used in the app now and are probably more trouble than they are worth since all we are doing is validating  that the passwords match and are over 8 characters.

**Comment by williamhoos** [comment]
for #1 above, I'm a much bigger fan of auto-login following password reset. If there is no redirect place to send people, I'd suggest send them to the site default page? That said, if this all takes place in a couple minute period, if there is a way to get the referring location for someone who requested the reset, that would be a logical behavior.

**Comment by hifilorau** [comment]
@williamhoos update. Tony and I just hooked the front end up together w the update pw mutation and it seems to be working locally. @Tonyynot14 needs to still make a minor change w the email routing to do a full test w an active token and make sure the the redirect works w the jwt we get back. But that should be a minimal amount of work.  

Last step will be:
Fixing mailgun issue on prod and maybe configing for staging so we can also test there? Is that correct @Tonyynot14
