### ISSUE TITLE
Sort order bug - facets on side-bar and presearch have strange number sort behavior

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#401]
Works on experimental. Think something must have gotten lost in merge. @blatde91 can you check out your branch and the new staging branch and see whta the difference in sort is?

**Comment by blatde91** [comment]
some of the weird issues are created by the new field "allow missing".

mostly the weird issues are caused by sorting descending and the interactions with ininitescroll.
things keep getting prepended on scroll, creating a buggy user experience. Any ideas on how to improve this behavior @ericharding ?

**Comment by ericharding** [comment]
After we pre-pend the new items just sort the whole collection again.  In theory the new set is already sorted but I suspect that will be fast enough and takes care of a few corner cases.

**Comment by williamhoos** [comment]
Looks fixed. Still issue with results updating on facet changes but #407 I think handles it.
