### ISSUE TITLE
planning task - crowd annotations of ct.gov fields

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#64]
Also need to figure out how to have crowd edit or version of values linked things like 

study status
facilities status
facilities name
study type

Some could be handled with tags but need some structure to tags

**Comment by williamhoos** [comment]
👍

**Comment by williamhoos** [comment]
👍

**Comment by williamhoos** [comment]
👍

**Comment by williamhoos** [comment]
Bob, this is the other "bigger" one we need to discuss - how to map a crowd annotation on "overall_status" in studies table and display crowd annotation value next to actual studies table value. May also need to allow faceted filter by some of these more structured crowd values.

**Comment by relwell** [comment]
I might need a better explanation on this one -- let's de-prioritize it until our next conversation

**Comment by williamhoos** [comment]
I'll leave in priority but remove from milestone

**Comment by relwell** [comment]
I think the way we want to handle this is by creating a table called "crowd field" for the study model. We can then configure any method or attribute of the model to first check whether a crowd field exists for that model, and deliver that layer of data over what's in AACT.

So for instance study status in AACT might be n/a for Study with an nct_id of X.

If we have an entry for "overall_status" in the CrowdField model for that nct_id, we'll know to use that data, use it in search, and write to the CrowdField model when making a change.

Nested values, such as attributes of the "design" model, will require a method in Study model that retrieves the value of the design model, so that we can override that method.
