### ISSUE TITLE
Research why clear is creating infinite loop after a new breadscrumb is added.

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#699]

**Comment by bespinosa01** [comment]
There seems to be a lot of redundant calls to update state with our params. And I think this is causing a mismatch when updating the state from the hash. In SearchPage in the handleClearFilters() and the handleResetFilters() functions we set the state to our new params and then call updateSearchParams, which again sets the state and based on that pushes us to the url with new hash. 

To test my theory I removed the initial setState in handleClearFilters and handleResetFilters. Instead of setting our state and passing the state down as an argument, I just call handleUpdateParams and pass the new parameters as an argument. This got rid of the infinite loop and seems to be working pretty well.
