### ISSUE TITLE
Fix password reset

### ISSUE THREAD

**Issue by relwell** [clinwiki-org/clinwiki#73]

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
👍

**Comment by relwell** [comment]
3 hours worth of work -- hoping this is just a backend  problem, but do need to hook the login form parts into this

**Comment by SearchSpecifics** [comment]
I am trying to Login to ClinWiki Dev and Production but it seems I'm unsuccessful.  On one unsuccessful attempt before today 08 August 2017 I tried a Recover Password.  In doing so does that make your current password null and void?

Also there seems to be no feedback from the webpage that an incorrect password attempt has been made, the number of attempts etc. I guess a valid entry seems to be if your name is showing in the [Login | Signup] button in the upper right hand corner of the page; your login has been successful.

Has login been shut-off while you're addressing this issue?

**Comment by SearchSpecifics** [comment]
I'm RETRACTING the issue I raised about not being able to log-in. The problem was between the chair and the keyboard. I simply was using the wrong Username.

With my login credentials always in place and valid, whatever the status of the password reset may be at this juncture is really irrelevant.  My apologies for any wild goose chase I may have induced. But I don't see any commentary hopefully no time and resources have been wasted

**Comment by williamhoos** [comment]
need to check if password reset is working and fix
