### ISSUE TITLE
Planning task for dimensions in ratings

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#80]
#59 Review plan and estimate for supporting dimensions and develop tiered approach to basic functionality with more sophisticated options in future

**Comment by relwell** [comment]
Probably a half hour or less for this one -- we already have a decent proposal in the original issue

**Comment by relwell** [comment]
Model and database migration for review dimension: 1.5 hr

Endpoint for displaying all available tags: half hour

Updating the review view to display "dropdown or create new" for a given dimension, and then adding a rating for it: 1.5 hr

Updating backend to save new dimensions: 0.5hr

Adding support for displaying default dimensions based on tagging in reviews: 3-5hrs, needs additional database models, and either command-line support (simpler) or some kind of backend admin support for actually associating the tags

Updating search to accommodate tags: 2-5hr. Putting a high estimate on this one because of indexing requirements, and also I worry that the dimensionality we'll introduce will be somewhat expensive.

**Comment by williamhoos** [comment]
When we do call to finalize approach, let's discuss the search accommodation and expense - let's work out ideas up front a little more in case it impacts implementation of dimensions

May need to clarify the other parts too - meaning of endpoint to display available tags (dimensions?) - examples from web?

**Comment by williamhoos** [comment]
This works but needs some additional strructure - probably should have an admin functionality to add choices to the list and the potential to link the list to other keywords or tags (ie Musella Foundation tagged studies could have custom list of dimensions for rating.

Also need better display and search of dimensions (graphs, search results)
