### ISSUE TITLE
Reviews not showing in search results

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#83]
I added a review for this study but star rating isn't showing in search results? Is there a delay in indexing or did the reindex on save get broken?

http://clinwiki-prod.herokuapp.com/study/NCT02858895

Also, sometimes when searching/researching the NCT number, sometimes get "undefined" with ~130 search results? Not reliably happening but mentioning if it triggers a look at potential issue.

**Comment by williamhoos** [comment]
this is showing correctly in search now.  Could have just overlapped when the AACT system was down or resolved somehow, so probably worth a couple minute to investigate and if not obvious answer, wait for it to happen again.

**Comment by relwell** [comment]
I was able to observe that adding a review makes its way into the search index in under a minute on prod. I tailed the logs and observed that there was maybe a 30 second gap between when the review was written and when the batch processor picked up the job. I think this is an acceptable gap, since at scale, this approach helps to reduce load on both the database and Elasticsearch.
