### ISSUE TITLE
export search results excel / csv

### ISSUE THREAD

**Issue by williamhoos** [clinwiki-org/clinwiki#84]
would like to have ability "export" the list of search results displayed on the search page.

At simplest level, could just be list of NCT_ID.  
At more ideal level, would include all the columns in the search results

Potentially even need to include other values not yet included but this can be 2nd phase.

**Comment by williamhoos** [comment]
![image](https://user-images.githubusercontent.com/19411659/28099619-922ed8f4-668b-11e7-8c4c-7628ea32c79c.png)

**Comment by crispmark** [comment]
Implemented in #93 and [cw-app #1](https://github.com/clinwiki-org/cw-app/pull/1).

**Comment by williamhoos** [comment]
here is a different search that would be an example to export:

https://clinwiki-prod.herokuapp.com/search/45DrU4ti

**Comment by relwell** [comment]
My current plan for this:

1) Create a new model called SearchExports that will associate a user ID to a given search hash and s3 URL.

2) Create a Sidekiq worker that will take the ID of the SearchExport model as its argument. It will create a CSV export asynchronously by using the arguments from the search hash as parameters for the Elasticsearch `scroll` API. This is required to accommodate more than 10,000 records in a search results set.

3) Add a mutation to the GraphQL API to create an instance of the SearchExport model, and trigger the Sidekiq worker responsible for processing the export.

4) Add a button to the upper right hand corner of the following view to "export to CSV":

![image](https://user-images.githubusercontent.com/232917/80285744-06f43a80-86f5-11ea-9f07-f18ce4b5e27a.png)

This will trigger that mutation, and display a modal acknowledging the export request, and link the user to a list of their requested CSV exports.

5) Once the CSV has been successfully generated, we will write the file to an S3 bucket. This means we will need an AWS account so that we can create this bucket. Another option would be to write these to disk, but this isn't a good idea since it doesn't scale past one server. We will also write the S3 URL to the SearchExport instance at hand.

6) Expose these SearchExport objects in the GraphQL API. 

7) Add a new route in the UI accessible through logged in user dropdown in the upper right hand corner.

![image](https://user-images.githubusercontent.com/232917/80285754-12476600-86f5-11ea-8868-b3526734aee6.png)

This new route will provide a paginated table of Search Exports, with download links for completed exports. If an export hasn't yet been completed, it will present to the user as "in progress".

In the future, if we're looking for something more responsive, we can use everything that's been built here, and add in a query to poll for a specific search export ID until the S3 URL has been populated, and then trigger a modal to display a download link
